sudo: required
services:
- docker
env:
  global:
  - DOCKER_CMD="docker run -it -e CGO_ENABLED=0 --rm -v $PWD:/go/src/github.com/liimaorg/liimactl -w
    /go/src/github.com/liimaorg/liimactl"
  - DOCKER_IMG="golang:alpine"
install:
- "$DOCKER_CMD -e GOOS=linux   -e GOARCH=amd64 $DOCKER_IMG sh -c 'go build -o out/liimactl-$GOOS-$GOARCH'"
- "$DOCKER_CMD -e GOOS=windows -e GOARCH=amd64 $DOCKER_IMG sh -c 'go build -o out/liimactl-$GOOS-$GOARCH.exe'"
- "$DOCKER_CMD -e GOOS=darwin  -e GOARCH=amd64 $DOCKER_IMG sh -c 'go build -o out/liimactl-$GOOS-$GOARCH'"
script:
- "$DOCKER_CMD $DOCKER_IMG go test -v ./..."
deploy:
  provider: releases
  api_key:
    secure: vO73wpfZPK8+bj+5ulxkaYeGcRzjb0obKJZrU8Y4wGNkd6DFujACpEasdZd71erM/7h5b93r3++fjPLIiznPq9ccqP3xQ2eIK5VRHvHG8a/c8mVsMP/8hpVdRS9/1kbx3T02Sqh1LSYoI8I5oOfB3SfMrbcCw9Yd8ifGNRaxjYJsgXoLOOGq/cGFU6rrjfIKFSp4Scb1ZdVUb/3hpKXPBNMIx0hKGplryLK/YbvdyXF9NORH1KqtCTeE7xAsEbJANwbM28JMwrwgq3mk7SrlladZ98EDuefQGoN/YYmseOX8XnJx7O+Y6DgCNMm7HG+jV6O6KfwAh/1QZcz+ECwcOnyugEtBspEHzCa15QSJIm1AcpiwejDdnDtXeubAEAT5MqFWq/VdqHh20WJLkkfviITvVFnY+2MOzGMEVwWiLwpOIwPtl9jEM1pkCsJG8OTS7TcIUKJpbl9eGg914RmN1fYdpB33Nr+ZE/cpMRHihPp8U2n/j1Rw5iPvKwQYkzKTKRwp6MVskZatAWyMik1WNfCYfOns99BABrlqIIhukfVKPZI2GhRQgAvdHCI+nyS67mGfKPW1QY6ummaj6EebT6tBxEk07I55tI/HjswcL01GpCZzUf8tpTG7Pzfj5O0IJhcKEnKdCvpXLvrp4XsVIzT3u56Nh0eq5Jz0BWOD34w=
  file_glob: true
  file: "out/*"
  skip_cleanup: true
  on:
    tags: true
    repo: liimaorg/liimactl
