name: release
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  test:
    name: release
    runs-on: ubuntu-latest
    container:
      image: golang:alpine
      env:
        CGO_ENABLED: "0"
        GOARCH: amd64
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Test
      run: go test -v ./...
    - name: Build linux
      env:
        GOOS: linux
      run: go build -o out/liimactl-$GOOS-$GOARCH
    - name: Build windows
      env:
        GOOS: windows
      run: go build -o out/liimactl-$GOOS-$GOARCH
    - name: Build darwin
      env:
        GOOS: darwin
      run: go build -o out/liimactl-$GOOS-$GOARCH
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: out/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}